### ISSUE TITLE
Separate the code from configuration

### ISSUE THREAD

**Issue by sagar-chopade** [TejasAvhad99/Practice#9]
Separate the code from configurations. 
configurations such as database connection details, SMTP config details, secrets, certificates should be separated from code. This has below advantages. Configurations can be injected through environment variables.
- Configurations can be injected externally without making changes to the code
- Same code be deployed in different environments. each environment will inject its own configuration during deployment.

**Comment by TejasAvhad99** [comment]
Successfully completed as directed
